name: self

on:
  workflow_dispatch:

jobs:
  mirror_transition:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build
        shell: bash
        run: cd $GITHUB_WORKSPACE/docker; source build.sh
